#!/usr/bin/env bash
[[ $DEBUG ]] && set -x
set -o errexit


help_doc() {
	{ read -r -d '' || :; [[ $REPLY == '|'* ]] && REPLY=${REPLY:1}; printf '%s' "${REPLY//$'\n|'/$'\n'}"; } <<-'HelpDoc'
		|matrix-request-access-token [ARGUEMENT...] [--] [BASE_URL]

		|A curl wrapper for requesting an access token from a matrix homeserver.

		|DEPENDENCIES
		|	curl

		|ARGUEMENT
		|	-u|--user USER
		|	--auth-url-user-pass AUTH_FILE   File containing a BASE_URL, user and password
		|	--auth-user-pass AUTH_FILE       File containing a user and password
		|	--auth-pass AUTH_FILE            File containing a password
		|	--dry-run                        Do everything except send the request
		|	--debug                          Output debugging information
		|	-h|--help                        Print help doc
		|	BASE_URL                         Homeserver base url

		|AUTH_FILE
		|	Path to a newline deliminated file containing values ordered as described by
		|	the ARGUEMENT. Lines in excess of these values are treated as comments.
		|	If the path is a hyphen (-), contents are read from stdin.

		|ENVIRONMENT
		|	MATRIX__BASE_URL   Base url of the Matrix homeserver
		|	MATRIX__USER       Account username, not including @...

		|VALUE PRIORITY
		|	ARGUEMENT value > AUTH_FILE value > ENVIRONMENT value

		|EXAMPLES
		|	# Enter missing information interactively
		|	matrix-request-access-token 'https://myhomeserver.org'
		|
		|	# Create an auth file
		|	>'/path/to/auth'
		|	chmod 600 -- '/path/to/auth'
		|	cat <<-'EOF' > '/path/to/auth'
		|		https://myhomeserver.org
		|		myuser
		|		mypass
		|	EOF
		|
		|	# Headless request
		| 	matrix-request-access-token --auth-url-user-pass '/path/to/auth'
		|
		|	# Headless request using a variety of inputs
		|	MATRIX__BASE_URL='https://matrix-client.matrix.org' \
		|	matrix-request-access-token -u 'myuser' --auth-pass <( printf '%s\n' 'mypass' )
	HelpDoc
	[[ $1 ]] && exit "$1"
}



print_stderr() {
	if [[ $1 == '0' ]]; then
		[[ $2 ]] && printf "$2" "${@:3}" 1>&2 || :
	else
		[[ $2 ]] && printf '%s'"$2" "ERROR: ${0##*/}, " "${@:3}" 1>&2 || :
		exit "$1"
	fi
}



user=
base_url=
base_urls=()
auth_path=
auth_path_vars=()
debug=
dry_run=
while [[ $1 ]]; do
	case $1 in
		'--user'|'-u')
			shift; user=$1 ;;
		'--auth-url-user-pass')
			shift; auth_path=$1; auth_path_vars=(base_url user pass);;
		'--auth-user-pass')
			shift; auth_path=$1; auth_path_vars=(user pass);;
		'--auth-pass')
			shift; auth_path=$1; auth_path_vars=(pass);;
		'--dry-run')
			dry_run=1 ;;
		'--debug')
			debug=1 ;;
		'--help'|'-h')
			help_doc 0 ;;
		'--')
			shift; break ;;
		'-'*)
			print_stderr 1 '%s %q\n' 'unrecognized parameter:' "$1" ;;
		*)
			base_urls+=("$1") ;;
	esac
	shift
done
base_urls+=("$@")



# Check dependencies
type curl 1>/dev/null



# Load auth file if provided
load_auth_file() {
	# input vars: auth_path, auth_path_vars
	# output vars: ${auth_path_vars[@]}
	local file_str var_name

	[[ $auth_path == '-' ]] && auth_path='/proc/self/fd/0'
	file_str=$(<"$auth_path")

	# Read each line into each variable name in ${auth_path_vars[@]} and ignore the rest
	IFS=$'\n' read -r -d '' "${auth_path_vars[@]}" _ < <(printf '%s\0' "$file_str")

	if [[ $debug ]]; then
		printf '%s\n' "Read values from ${auth_path@Q}:" 1>&2
		for var_name in "${auth_path_vars[@]}"; do
			printf '%s\n' "  $var_name=${!var_name}" 1>&2
		done
		printf '\n' 1>&2
	fi
fi
[[ $auth_path ]] && load_auth_file



# Define function for setting the value of a parent variable
prompt() {
	local read_prompt=$1 read_var=$2 visibility=$3 read_params=()

	[[ $visibility == 'show' || $visibility == 'hide' ]] || print_stderr 1 '%s\n' "bad use of prompt() params: ${*@Q}"

	# stdin must be connected to a terminal
	[[ -t 0 ]] || return 1

	[[ $visibility == 'hide' ]] && read_params+=('-s')
	read_params+=('-r' '-p' "${read_prompt} " "$read_var")

	IFS= read "${read_params[@]}" < /dev/tty

	[[ $visibility == 'hide' ]] && printf '\n' 1>&2
	[[ ! ${!read_var} ]] && return 4
	return 0
}



# Settle defining of homeserver base_url with interactive fallback
if [[ ${#base_urls[@]} == '0' ]]; then
	# base url not in params

	if [[ ! $base_url ]]; then
		# base url not in file
		base_url=$MATRIX__BASE_URL
		[[ $base_url ]] || prompt 'Enter base url (ex: https://matrix-client.matrix.org):' 'base_url' 'show' || print_stderr 1 '%s\n' 'no homeserver base url given'
	fi

else
	[[ ${#base_urls[@]} != '1' ]] && print_stderr 1 '%s\n' 'more than one base url parameter given'
	base_url=${base_urls[0]}
fi



# Settle defining of user and pass with interactive fallback
: ${user:=$MATRIX__USER}
[[ $user ]] || prompt 'Enter username (ex: myuser):' 'user' 'show' || print_stderr 1 '%s\n' 'no user provided'
[[ $pass ]] || prompt 'Enter password:' 'pass' 'hide' || print_stderr 1 '%s\n' 'no password provided'



if [[ $debug ]]; then
	printf '%s\n' "Using values:" 1>&2
	printf '%s\n' "  base_url=${base_url}" 1>&2
	printf '%s\n' "  user=${user}" 1>&2
	printf '%s\n' "  pass=${pass}" 1>&2
	printf '\n' 1>&2
fi



# Define JSON for request
json_encode() {
	local -n 'json_encode__str='"$1"
	json_encode__str=${json_encode__str//\\/\\\\}
	json_encode__str=${json_encode__str//\"/\\\"} #"
	json_encode__str=${json_encode__str//$'\n'/\\n}
	json_encode__str=${json_encode__str//$'\t'/\\t}
}
json_encode user
json_encode pass



{ read -r -d '' req_json || :; } <<-EOF
	{
		"identifier": {
			"type": "m.id.user",
			"user": "${user}"
		},
		"password": "${pass}",
		"type": "m.login.password"
	}
EOF
req_json=${req_json//,$'\n'/', '}
req_json=${req_json//$'\n'}



if [[ $debug ]]; then
	printf '%s\n' "req_json=${req_json}"

	curl() {
		printf '%s ' 'curl' "${@@Q}" 1>&2; printf '\n---\n' 1>&2
		[[ $dry_run ]] || curl "$@"
	}
elif [[ $dry_run ]]; then
	exit 0
fi



# Send request
curl \
	-X POST \
	-H 'Content-Type: application/json' \
	-d @<(printf '%s' "$req_json") \
	"${base_url}/_matrix/client/v3/login"



[[ -t 0 ]] && printf '\n' 1>&2
exit 0



